### ISSUE TITLE
AttributeError: 'module' object has no attribute 'toimage'

### ISSUE THREAD

**Issue by c1a1o1** [david-gpu/srez#14]
Traceback (most recent call last):
  File "srez_main.py", line 190, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "srez_main.py", line 187, in main
    _train()
  File "srez_main.py", line 179, in _train
    srez_train.train_model(train_data)
  File "/home/caocao/srez-master/srez_train.py", line 107, in train_model
    _summarize_progress(td, test_feature, test_label, gene_output, batch, 'out')
  File "/home/caocao/srez-master/srez_train.py", line 30, in _summarize_progress
    scipy.misc.toimage(image, cmin=0., cmax=1.).save(filename)
AttributeError: 'module' object has no attribute 'toimage'

**Comment by david-gpu** [comment]
If you look at the last two lines of the traceback you can see that the problem comes from scipy. Most likely it requires a newer version of scipy than what you are currently using.

Please be advised that with this software you will **not** be able to upscale your own images. It's just a demo, a prototype. If you want to upscale your own images I would advise you to try something like [https://github.com/alexjc/neural-enhance](https://github.com/alexjc/neural-enhance), but please keep in mind I have never used that software and can't provide any help on how to use it.

**Comment by c1a1o1** [comment]
Thanks  very much
