### ISSUE TITLE
Why i can't run this code??

### ISSUE THREAD

**Issue by evilpeach** [david-gpu/srez#16]
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 980 Ti
major: 5 minor: 2 memoryClockRate (GHz) 1.228
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 5.61GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 965, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 947, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [] rhs shape= [256]
	 [[Node: gene/GEN_L006/BatchNorm/beta/Assign = Assign[T=DT_FLOAT, _class=["loc:@gene/GEN_L006/BatchNorm/beta"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](gene/GEN_L006/BatchNorm/beta, gene/GEN_L006/BatchNorm/beta/Initializer/zeros)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "srez_main.py", line 190, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "srez_main.py", line 187, in main
    _train()
  File "srez_main.py", line 179, in _train
    srez_train.train_model(train_data)
  File "/home/mumu/Desktop/DCGAN-srez/srez_train.py", line 68, in train_model
    td.sess.run(tf.initialize_all_variables())
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [] rhs shape= [256]
	 [[Node: gene/GEN_L006/BatchNorm/beta/Assign = Assign[T=DT_FLOAT, _class=["loc:@gene/GEN_L006/BatchNorm/beta"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](gene/GEN_L006/BatchNorm/beta, gene/GEN_L006/BatchNorm/beta/Initializer/zeros)]]
Caused by op 'gene/GEN_L006/BatchNorm/beta/Assign', defined at:
  File "srez_main.py", line 190, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "srez_main.py", line 187, in main
    _train()
  File "srez_main.py", line 166, in _train
    srez_model.create_model(sess, noisy_train_features, train_labels)
  File "/home/mumu/Desktop/DCGAN-srez/srez_model.py", line 402, in create_model
    _generator_model(sess, features, labels, channels)
  File "/home/mumu/Desktop/DCGAN-srez/srez_model.py", line 365, in _generator_model
    model.add_residual_block(nunits, mapsize=mapsize)
  File "/home/mumu/Desktop/DCGAN-srez/srez_model.py", line 214, in add_residual_block
    self.add_batch_norm()
  File "/home/mumu/Desktop/DCGAN-srez/srez_model.py", line 51, in add_batch_norm
    out = tf.contrib.layers.batch_norm(self.get_output(), scale=scale)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 171, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 186, in batch_norm
    trainable=trainable)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 171, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 266, in model_variable
    caching_device=caching_device, device=device)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 171, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 230, in variable
    caching_device=caching_device)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 873, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 700, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 217, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 202, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 536, in _get_single_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variables.py", line 211, in __init__
    dtype=dtype)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variables.py", line 313, in _init_from_args
    validate_shape=validate_shape).op
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

What is a problem?? This error has happened when i use "python3 srez_main.py --run train" 
and my dataset is celebAface which is the same as instructor

**Comment by david-gpu** [comment]
I saw that kind of error when I had an old version of Tensorflow. Have you
tried updating it?

**Comment by evilpeach** [comment]
That problem's solved. Thank you so much :)
