### ISSUE TITLE
AttributeError: close  at python3 srez_main.py --run demo

### ISSUE THREAD

**Issue by loveJasmine** [david-gpu/srez#19]
rzai@rzai00:~/prj/srez$ CUDA_VISIBLE_DEVICES=1 python3 srez_main.py --run demo
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.52GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
WARNING:tensorflow:From /home/rzai/prj/srez/srez_model.py:366 in _generator_model.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
...
Producing video file...
Traceback (most recent call last):
  File "srez_main.py", line 190, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "srez_main.py", line 185, in main
    _demo()
  File "srez_main.py", line 134, in _demo
    srez_demo.demo1(sess)
  File "/home/rzai/prj/srez/srez_demo.py", line 25, in demo1
    clip      = mpe.ImageSequenceClip(filenames, fps=fps)
  File "/usr/local/lib/python3.4/dist-packages/moviepy/video/io/ImageSequenceClip.py", line 104, in __init__
    if with_mask and (make_frame(0).shape[2]==4):
  File "/usr/local/lib/python3.4/dist-packages/moviepy/video/io/ImageSequenceClip.py", line 99, in make_frame
    self.lastimage = imread(self.sequence[index])[:,:,:3] 
  File "/usr/local/lib/python3.4/dist-packages/imageio/core/functions.py", line 187, in imread
    return reader.get_data(0)
  File "/usr/local/lib/python3.4/dist-packages/imageio/core/format.py", line 232, in __exit__
    self.close() 
  File "/usr/local/lib/python3.4/dist-packages/imageio/core/format.py", line 247, in close
    self._close()
  File "/usr/local/lib/python3.4/dist-packages/imageio/plugins/pillow.py", line 93, in _close
    self._im.close()
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: close

**Comment by david-gpu** [comment]
What version of moviepy and imageio are you using? The problem appears to be there.
