### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to remov e a directory: train

### ISSUE THREAD

**Issue by kingson999** [david-gpu/srez#32]
Hi,

I repeat the program on Tensorflow 1.2.0rc0, CPU version,
There is below hint, 
How should I solve it ? 

(C:\ProgramData\Anaconda3\envs\tensorflow) D:\AI\srez>python srez_main.py --run
train
2017-05-31 10:33:28.029651: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE instructions, but these are available on your m
achine and could speed up CPU computations.
2017-05-31 10:33:28.029651: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE2 instructions, but these are available on your
machine and could speed up CPU computations.
2017-05-31 10:33:28.029651: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE3 instructions, but these are available on your
machine and could speed up CPU computations.
2017-05-31 10:33:28.029651: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.1 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-05-31 10:33:28.029651: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.2 instructions, but these are available on you
r machine and could speed up CPU computations.
Traceback (most recent call last):
2017-05-31 10:33:28.123251: E c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\util\events_writer.cc:162] The events file train\ev
ents.out.tfevents.1496198008.PC has disappeared.
2017-05-31 10:33:28.123251: E c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\util\events_writer.cc:131] Failed to flush 1 events
 to train\events.out.tfevents.1496198008.PC
  File "srez_main.py", line 191, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\py
thon\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "srez_main.py", line 188, in main
    _train()
  File "srez_main.py", line 146, in _train
    all_filenames = prepare_dirs(delete_train_dir=True)
  File "srez_main.py", line 76, in prepare_dirs
    tf.gfile.DeleteRecursively(FLAGS.train_dir)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\py
thon\lib\io\file_io.py", line 432, in delete_recursively
    pywrap_tensorflow.DeleteRecursively(compat.as_bytes(dirname), status)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\contextlib.py", line 66, in
 __exit__
    next(self.gen)
  **File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\py
thon\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to remov
e a directory: train**

**Comment by crimsonxiii** [comment]
See #28

**Comment by kingson999** [comment]
that is fine, and running OK, thanks!
