### ISSUE TITLE
 Failed to remove a directory: train

### ISSUE THREAD

**Issue by chenjinxin3140101848** [david-gpu/srez#43]
I try to run the project by typing the suggested codes "python srez_main.py --run train"
but failed with the message " **Failed to remove a directory: train**"

Sincerely look for your help~ 
#  **the following part is the detail:**

"
F:\机器学习\sre-master\srez-master>python srez_main.py --run train
2017-09-29 15:35:11.171035: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-09-29 15:35:11.171198: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-29 15:35:11.172735: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-29 15:35:11.174953: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-29 15:35:11.175738: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-29 15:35:11.176498: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "srez_main.py", line 191, in <module>
    tf.app.run()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "srez_main.py", line 188, in main
    _train()
  File "srez_main.py", line 146, in _train
    all_filenames = prepare_dirs(delete_train_dir=True)
  File "srez_main.py", line 75, in prepare_dirs
    tf.gfile.DeleteRecursively(FLAGS.train_dir)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 432, in delete_recursively
    pywrap_tensorflow.DeleteRecursively(compat.as_bytes(dirname), status)
  File "D:\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to remove a directory: train
"

**Comment by JachenL** [comment]
你好，我运行代码的时候也出现了一样的问题，请问你决解了吗？

**Comment by tstc435** [comment]
146行，all_filenames = prepare_dirs(delete_train_dir=True)
改成不删除好了：
    all_filenames = prepare_dirs()

**Comment by JachenL** [comment]
改成不删除后能训练，但是loss不更新

**Comment by aanchalMongia** [comment]
see #28 [https://github.com/david-gpu/srez/issues/28](url)
