### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by shede1988** [david-gpu/srez#46]
Progress[  0%], ETA[  20m], Batch [  10], G_Loss[0.173], D_Real_Loss[0.556], D_Fake_Loss[1.341]
Progress[  0%], ETA[  20m], Batch [  20], G_Loss[0.162], D_Real_Loss[0.665], D_Fake_Loss[0.738]
Progress[  0%], ETA[  20m], Batch [  30], G_Loss[0.149], D_Real_Loss[0.677], D_Fake_Loss[0.755]
Progress[  0%], ETA[  20m], Batch [  40], G_Loss[0.144], D_Real_Loss[0.775], D_Fake_Loss[0.764]
Progress[  0%], ETA[  20m], Batch [  50], G_Loss[0.136], D_Real_Loss[0.700], D_Fake_Loss[0.661]
Progress[  0%], ETA[  20m], Batch [  60], G_Loss[0.122], D_Real_Loss[0.682], D_Fake_Loss[0.760]
Progress[  0%], ETA[  20m], Batch [  70], G_Loss[0.132], D_Real_Loss[0.674], D_Fake_Loss[0.646]
Progress[  0%], ETA[  20m], Batch [  80], G_Loss[0.135], D_Real_Loss[0.738], D_Fake_Loss[0.648]
Progress[  0%], ETA[  20m], Batch [  90], G_Loss[0.141], D_Real_Loss[0.702], D_Fake_Loss[0.705]
Progress[  0%], ETA[  20m], Batch [ 100], G_Loss[0.126], D_Real_Loss[0.698], D_Fake_Loss[0.668]
Progress[  0%], ETA[  20m], Batch [ 110], G_Loss[0.128], D_Real_Loss[0.651], D_Fake_Loss[0.702]
Progress[  0%], ETA[  20m], Batch [ 120], G_Loss[0.142], D_Real_Loss[0.676], D_Fake_Loss[0.668]
Progress[  0%], ETA[  20m], Batch [ 130], G_Loss[0.113], D_Real_Loss[0.660], D_Fake_Loss[0.686]
Progress[  0%], ETA[  20m], Batch [ 140], G_Loss[0.125], D_Real_Loss[0.676], D_Fake_Loss[0.613]
Progress[  0%], ETA[  20m], Batch [ 150], G_Loss[0.127], D_Real_Loss[0.671], D_Fake_Loss[0.682]
Progress[  0%], ETA[  20m], Batch [ 160], G_Loss[0.145], D_Real_Loss[0.642], D_Fake_Loss[0.690]
Progress[  0%], ETA[  20m], Batch [ 170], G_Loss[0.126], D_Real_Loss[0.658], D_Fake_Loss[0.698]
Progress[  0%], ETA[  20m], Batch [ 180], G_Loss[0.122], D_Real_Loss[0.631], D_Fake_Loss[0.664]
Progress[  0%], ETA[  20m], Batch [ 190], G_Loss[0.128], D_Real_Loss[0.626], D_Fake_Loss[0.647]
Progress[  0%], ETA[  20m], Batch [ 200], G_Loss[0.120], D_Real_Loss[0.676], D_Fake_Loss[0.619]
Traceback (most recent call last):
  File "srez_main.py", line 190, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "srez_main.py", line 187, in main
    _train()
  File "srez_main.py", line 179, in _train
    srez_train.train_model(train_data)
  File "/home/alan/srez-master/srez_train.py", line 107, in train_model
    _summarize_progress(td, test_feature, test_label, gene_output, batch, 'out')
  File "/home/alan/srez-master/srez_train.py", line 22, in _summarize_progress
    image   = tf.concat(2, [nearest, bicubic, clipped, label])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by aanchalMongia** [comment]
In srez_train.py, replace
line#22-> image   = tf.concat(2, [nearest, bicubic, clipped, label])
and
lin#25-> image = tf.concat(0, [image[i,:,:,:] for i in range(max_samples)])

with:

image   = tf.concat( [nearest, bicubic, clipped, label],2)
and
image = tf.concat( [image[i,:,:,:] for i in range(max_samples)],0)

(problem arises due to tensorflow version mismatch)
