### ISSUE TITLE
ValueError: Shapes (4, 16, 64, 64, 3) and () are incompatible

### ISSUE THREAD

**Issue by aezco** [david-gpu/srez#62]
I am receiving the following error, just downloaded your code and runned with the celebA aligned cropped folder, without resizing images or changing anything.

`Traceback (most recent call last):
  File "srez_main.py", line 190, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "srez_main.py", line 187, in main
    _train()
  File "srez_main.py", line 179, in _train
    srez_train.train_model(train_data)
  File "/Users/aez/Desktop/caffetokeras-vgg16/super-resolution/srez-master/srez_train.py", line 107, in train_model
    _summarize_progress(td, test_feature, test_label, gene_output, batch, 'out')
  File "/Users/aez/Desktop/caffetokeras-vgg16/super-resolution/srez-master/srez_train.py", line 22, in _summarize_progress
    image   = tf.concat(2, [nearest, bicubic, clipped, label])
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 1254, in concat
    tensor_shape.scalar())
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1023, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (4, 16, 64, 64, 3) and () are incompatible`

**Comment by 1702609** [comment]
I got the same error. Is there a fix for this?
